### ISSUE TITLE
ModuleNotFoundError: No module named 'network_dismantling.machine_learning'

### ISSUE THREAD

**Issue by c0mm4nd** [NetworkDismantling/review#7]
```
2024-04-07 23:39:39 :: ERROR    :: MainProcess :: Error while dismantling network dblp-cite: No module named 'network_dismantling.machine_learning'                                                                              
Traceback (most recent call last):
  File "/home/ta/c0mm4nd/netlab/review/network_dismantling/dismantler.py", line 326, in main
    runs = dismantling_method(
  File "/home/ta/c0mm4nd/netlab/review/network_dismantling/__init__.py", line 92, in __call__
    output = self.function(*args, **kwargs)
  File "/home/ta/c0mm4nd/netlab/review/network_dismantling/CoreGDM/python_interface.py", line 387, in CoreGDM
    return _CoreGDM(network, **kwargs)
  File "/home/ta/c0mm4nd/netlab/review/network_dismantling/CoreGDM/python_interface.py", line 295, in _CoreGDM
    from network_dismantling.CoreGDM.core_grid import parse_parameters
  File "/home/ta/c0mm4nd/netlab/review/network_dismantling/CoreGDM/core_grid.py", line 34, in <module>
    from network_dismantling.CoreGDM.core_network_dismantler import get_df_columns
  File "/home/ta/c0mm4nd/netlab/review/network_dismantling/CoreGDM/core_network_dismantler.py", line 34, in <module>
    from network_dismantling.GDM.network_dismantler import init_network_provider, \
  File "/home/ta/c0mm4nd/netlab/review/network_dismantling/GDM/network_dismantler.py", line 35, in <module>
    from network_dismantling.GDM.predictors import static_predictor, get_predictions, lcc_static_predictor
  File "/home/ta/c0mm4nd/netlab/review/network_dismantling/GDM/predictors.py", line 27, in <module>
    from network_dismantling.machine_learning.pytorch.training_data_extractor import (
ModuleNotFoundError: No module named 'network_dismantling.machine_learning'
```

BTW, `make` compiling the cpp codes would be better when installing the package, rather than running the program.

**Comment by eMarco** [comment]
Hi, I must have copy-pasted some old code in one of the last updates. Everything should work now.

Regarding the setup / run-time building of the heuristics, I might agree.
The main (and only?) reason we built them at run-time is that most of those implementations required parameters and input file names as constants / headers.
Once we're done implementing the boost CLI in every script, we can build everything at setup time.
I'll be pretty busy for a while, feel free to create a pull request!

Best,
M

**Comment by c0mm4nd** [comment]
Sorry for bothering you while you are busy, but I'm still facing the error. Clearly that in the main branch the dependency `network_dismandling.machine_learning` on  https://github.com/NetworkDismantling/review/blob/7d097214b54dfa554f5c166e4bf53eaf755bc82b/network_dismantling/GDM/predictors.py#L27 is missing

**Comment by c0mm4nd** [comment]
And `"ReinsertionSupport" is not defined` in this type hint:
 https://github.com/NetworkDismantling/review/blob/5fe9b60a1c513630a64e5d5df128eab930f4f980/network_dismantling/__init__.py#L59

**Comment by eMarco** [comment]
Thank you for reporting these errors and for the patience.
Again, I must have merged experimental/old code somewhere in the recent history of this project. 
I pushed two hot fixes, but I'll clone the repo in a new folder and test a things ASAP.
Let me know if you catch anything else in the meanwhile
